### ISSUE TITLE
impossible to use from my APP

### ISSUE THREAD

**Issue by IvanCouet** [ancarebeca/FullCalendarBundle#10]
Catchable Fatal Error: Argument 1 passed to PMAS\SearchBundle\EventListener\LoadDataListener::loadData() must be an instance of PMAS\SearchBundle\EventListener\CalendarEvent, instance of AncaRebeca\FullCalendarBundle\Event\CalendarEvent given 

The LoadDataListener from my apllcation is call with instance of AncaRebeca\FullCalendarBundle\Event\CalendarEvent

My services:
# src/PMAS/SearchBundle/Resources/config/services.yml

services:
    app_bundle.service.listener:
        class: PMAS\SearchBundle\EventListener\LoadDataListener
        tags:
            - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }

**Comment by BazylPL** [comment]
Need to add
use Path\To\Your\Entity\CalendarEvent; 

before LoadDataListener class

**Comment by ancarebeca** [comment]
Thanks Bazy
