### ISSUE TITLE
Symfony 3.0

### ISSUE THREAD

**Issue by nbspencer** [ancarebeca/FullCalendarBundle#17]
Hey does this bundle worked on symfony 3.0.4 ?

**Comment by ancarebeca** [comment]
Hi @nbspencer . At the moment FullCalendarBundle is not compatible with Symfony 3.0 but I'm working on that. My plan is push soon a new release.

**Comment by nbspencer** [comment]
Ok i'm Florian btw.

**Comment by ancarebeca** [comment]
Hi @nbspencer, FullCalendarBundle was updated to support Symfony 3.0
