### ISSUE TITLE
Unquoted scalars exception with Symfony 3.1

### ISSUE THREAD

**Issue by ohvitorino** [ancarebeca/FullCalendarBundle#19]
Hi,

While installing the bundle in my Symfony 3.1 app I get the following error.

```
[Symfony\Component\Yaml\Exception\ParseException]
    The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 9 (near "- @anca_rebeca_full_calendar.service.serializer").
```

The fix is very simple, I'll make a PR with the fix.

**Comment by SanderMuller** [comment]
I get this exact error as well. Please accept the suggestion posted by @ohvitorino

**Comment by ancarebeca** [comment]
@Rhinni a new version has been released. v3.0.1. Thanks @ohvitorino
