### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by iamthestreets** [ancarebeca/FullCalendarBundle#22]
Hi,

I might be asking this in the wrong place, but I'm a bit confused at how I use this.

I setup everything as instructed, but can't seem to see any data on the calendar. 
Do I need to create my own controller?
How do I access the calendar?

I created my own controller to load the view, but I don't see any data. Not sure what I'm missing.

**Comment by mgonyan** [comment]
Hi @iamthestreets,

Can you please add the code you are testing ?

**Comment by ancarebeca** [comment]
Hi @iamthestreets. I created a simple demo, I hope this will help you . https://github.com/ancarebeca/full-calendar-example

**Comment by garak** [comment]
Your demo is missing even the simplest thing you should include, an entity representing an event.
Also, you should add missing documentation to this bundle, since it's unclear how to use filters

**Comment by ancarebeca** [comment]
Thank you for your suggestions @garak. Yes it’s very simple because I was trying to show the simplest happy path but if you need further instructions feel free to open a new issue and tell me how I can help you.

**Comment by ancarebeca** [comment]
@iamthestreets Shall we close this?
