### ISSUE TITLE
Error on prod but not on dev

### ISSUE THREAD

**Issue by thibaultfalque** [ancarebeca/FullCalendarBundle#23]
Hello, 
Thank you for this bundle. 

I don't understand why I have this error on production but not on version dev. 
My prod configuration is in amazon elastic beanstalk server. The error is: 
TypeError: N is null

I have screenshot my javascript console:
![capture du 2017-01-13 22 56 21](https://cloud.githubusercontent.com/assets/6603358/21947202/440ae750-d9e4-11e6-8922-7d379dcd8451.png)

In my development version I haven't this problem. 

Any idea ? 

Thank you.

**Comment by mgonyan** [comment]
@thibaultfalque Can you describe your deployment process (SF part only) ?

**Comment by thibaultfalque** [comment]
@mgonyan Thank you for your answer. 
I think understand the problem I have a conflict with an other bundle: https://github.com/avanzu/AdminThemeBundle
But the problem is only on prod environment. It's symfony deployment in elastic beanstalk. 
I override the inclusion of AdminThemeBundle with your inclusion and it's ok. But I have an other problem with the jquery inclusion. It's very strange. 
![capture du 2017-01-25 22 39 23](https://cloud.githubusercontent.com/assets/6603358/22310388/61f23ac4-e34f-11e6-972a-e895e3d98d08.png)

**Comment by ancarebeca** [comment]
@thibaultfalque Do you still need help? Can I close this issue?
