### ISSUE TITLE
Can't override fullcalendar.default-settings.js

### ISSUE THREAD

**Issue by Boulboulouboule** [ancarebeca/FullCalendarBundle#30]
Hi !

I tried to override default jfull calendar settings by adding my own in **Resources/public/js/** like it is said in the documentations, but it doesn't seems to work. I also tried things like adding a **AncaRebecaFullCalendarBundle/fullcalendar/public/js/fullcalendar.default-settings.js** file, but nothing worked.

Can you help me with that ?

Thanks a lot !

**Comment by mgonyan** [comment]
Hi @Boulboulouboule, can you please provide more details about where are you storing the **js** files (within your bundle **YourBundle/Resources/public/js** or **app/Resources/public/js**), config files, Symfony version and as many details as you can provide. thanks.

**Comment by Boulboulouboule** [comment]
Hi @mgonyan !

My bad, I was storing the files in app/Resources/public/js..! I tried MyBundle/Resources/public/js and it works now.

Thanks for the quick help and sorry for the useless issue !
