### ISSUE TITLE
__construct() must be an instance of Doctrine\\ORM\\EntityManager

### ISSUE THREAD

**Issue by ibrasdev** [ancarebeca/FullCalendarBundle#40]
Hello, I dont know why i cant run the calendar in good way this is my files please help me its been 2 weeks that i try to solve that :

LoadData :

`<?php

namespace CMRBundle\EventListener;

use AncaRebeca\FullCalendarBundle\Event\CalendarEvent;
use AncaRebeca\FullCalendarBundle\Model\Event;
use AncaRebeca\FullCalendarBundle\Model\FullCalendarEvent;
use CMRBundle\Entity\Schedule;
use Doctrine\ORM\EntityManager;
class LoadDataListener
{
    /**
     * @var EntityManager
     */
    private $em;

    public function __construct(EntityManager $em)
    {
        $this->em = $em;
    }

    /**
     * @param CalendarEvent $calendarEvent
     *
     * @return FullCalendarEvent[]
     */
    public function loadData(CalendarEvent $calendarEvent)
    {
        // You can retrieve information from the event dispatcher (eg, You may want which day was selected in the calendar):
        // $startDate = $calendarEvent->getStart();
        // $endDate = $calendarEvent->getEnd();
        // $filters = $calendarEvent->getFilters();

        // You may want do a custom query to populate the events
        // $currentEvents = $repository->findByStartDate($startDate);
        $repository = $this->em->getRepository('CMRBundle:Schedule');
        $schedules = $repository->findAll();

        // You may want to add an Event into the Calendar view.
        /** @var Schedule $schedule */
        foreach ($schedules as $schedule) {
            $calendarEvent->addEvent(new Event($schedule->getTitle(), $schedule->getStart()));
        }
    }
} `

Schedule :

`<?php

namespace CMRBundle\EventListener;

use Doctrine\ORM\Mapping as ORM;

/**
 * Schedule
 *
 * @ORM\Table(name="schedule")
 * @ORM\Entity(repositoryClass="CMRBundle\Repository\ScheduleRepository")
 */
class Schedule
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="start", type="datetime")
     */
    private $start;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="end", type="datetime")
     */
    private $end;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Schedule
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @return \DateTime
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     * @return \DateTime
     */
    public function getEnd()
    {
        return $this->end;
    }

    /**
     * @param \DateTime $start
     */
    public function setStart($start)
    {
        $this->start = $start;
    }

    /**
     * @param \DateTime $end
     */
    public function setEnd($end)
    {
        $this->end = $end;
    }
}
`

And this is the error i dont understand what im missing : 
`{"error":"Catchable Fatal Error: Argument 1 passed to CMRBundle\\EventListener\\LoadDataListener::__construct() must be an instance of Doctrine\\ORM\\EntityManager, none given, called in C:\\wamp64\\www\\No\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 492 and defined"}`

Ive used the example available

**Comment by PATATESUPREME** [comment]
Hello @ibrasdev ,

Your class LoadDataListener looks like a service. If so you might have declared it in a service.yml.
Then did you place the right service in the arguments of this service ?

**Comment by ibrasdev** [comment]
Yes ive declared the service in services.yml of CMRBundle :
`    cmr.service.listener:
        class: CMRBundle\EventListener\LoadDataListener
        tags:
        - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }`

Thank you for helping

**Comment by PATATESUPREME** [comment]
Ok then to solve your error, you need to add to your service `cmr.service.listener` :
`arguments: ["@doctrine.orm.entity_manager"]`

**Comment by ibrasdev** [comment]
Thank you very much its been 2 weeks that i try to solve this much love !
But i have an other problem :
`Error: Cannot instantiate abstract class AncaRebeca\FullCalendarBundle\Model\Event`

its about :
`foreach ($schedules as $schedule) {            $calendarEvent->addEvent(new Event($schedule->getTitle(), $schedule->getStart()));        }`

**Comment by PATATESUPREME** [comment]
Look at the step 3 of the installation, You need to create a custom Entity that extends the Event class.

**Comment by ibrasdev** [comment]
I already created the Schedule entity and ive created 2 events on db but still have same errors

**Comment by PATATESUPREME** [comment]
I see, instead of adding your custom event Schedule, you should :
1. Extend the class event : 
```php
use AncaRebeca\FullCalendarBundle\Model\Event;

class Schedule extends Event {
```
2. Add the new custom event :
```php
foreach ($schedules as $schedule) {
    $calendarEvent->addEvent($schedule);
}
```
Then this should be good.

**Comment by ibrasdev** [comment]
Ive added what you said, the error seem to be fixed but i got a new error :( 
`Compile Error: Access level to CMRBundle\Entity\Schedule::$id must be protected`
My class Schedule must be empty ?

**Comment by PATATESUPREME** [comment]
Your class Schedule does'nt need to be empty. But if you open the class `AncaRebeca\FullCalendarBundle\Model\Event`, you will see some fields already existant.

There are many solutions to this issue :
- Don't duplicate the existant fields in your Schedule class.
- Or put protected instead of private to the duplicated fields in your Schedule class.

Pick the one you need.

**Comment by ibrasdev** [comment]
Hello, I think that i turn around, i got this error :
`Error: Call to a member function format() on null`

Its about :
` $event['start']             = $this->getStartDate()->format("Y-m-d\TH:i:sP");`

This is my class Schedule :
`class Schedule extends Event
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

}`

Ive just put the id and ive delete it from Event :
`
class Event implements EventInterface
{
    /**
     * @var string
     */
    protected $title;
    /**
     * @var boolean
     */
    protected $allDay = true;
    /**
     * @var \DateTime
     */
    protected $startDate;
    /**
     * @var \DateTime
     */
    protected $endDate;
    /**
     * @var string
...........`

**Comment by PATATESUPREME** [comment]
You have two issues here :
1. You are making the calendar bundle instable by deleting id of the Event class. My advice would be to restore Event as it was and then put protected on the Schedule $id. But that's not the reason of your issue.
2. Then format is generally called on Datetime properties. Where is this function used ?

**Comment by ibrasdev** [comment]
The function is used on Event.php :
`$event['start']             = $this->getStartDate()->format("Y-m-d\TH:i:sP");`

When i genetrate entities i only got the id field on the schedule table not all the fields from the Event

**Comment by PATATESUPREME** [comment]
Two ways again :
1. Change your fields in Schedule :
    In the Event class their is already $title and $startDate, so change :
    ```php
         private $start;
    ```
    to
    ```php
         protected $startDate;
    ```
2. Or instead of calling the event date, call the schedule date :
    ```php
        $event['start'] = $this->getStart()->format("Y-m-d\TH:i:sP");
    ```

**Comment by ibrasdev** [comment]
Hello,
Ive recreated Schedule Entity based on Event.php now i got all the fields on the db with protected.

I got this new error :
`{"error":"Could not convert database value \"\" to Doctrine Type array"}`

**Comment by ibrasdev** [comment]
Ma patate tu est ou i need you xD

**Comment by PATATESUPREME** [comment]
Are the data in your DB important ?
1. You could truncate the Schedule table
2. Or set the wrong values with an empty array in the DB like a:0:{}

**Comment by ibrasdev** [comment]
Yes ive generated a new table with all the fields in the Event.php
But when i try to load fixture i got this error :
`[Symfony\Component\Debug\Exception\ContextErrorException]                    
  Warning: Missing argument 1 for CMRBundle\Entity\Schedule::__construct(), c  
  alled in C:\wamp64\www\No\src\CMRBundle\DataFixtures\ORM\LoadScheduleData.p  
  hp on line 12 and defined`

This is the LoadScheduleData.php:
`public function load(ObjectManager $manager)
    {
        $schedule = new Schedule();
        $schedule->setTitle('Yoga class');
        $today = new \DateTime();
        $schedule->setStartDate($today);
        $schedule->setEndDate($today);
        $manager->persist($schedule);

        $schedule = new Schedule();
        $schedule->setTitle('German class');
        $tomorrow = new \DateTime('tomorrow');
        $schedule->setStartDate($tomorrow);
        $schedule->setEndDate($tomorrow);
        $manager->persist($schedule);

        $manager->flush();
    }`
its about : $schedule = new Schedule();

**Comment by ibrasdev** [comment]
Si if i have all the fields on the Schedule i must delete the extends Event ?

**Comment by PATATESUPREME** [comment]
No, but since you extends this class the __construct is diferent :
```php

    /**
     * @param string $title
     * @param \DateTime $start
     */
    public function __construct($title, \DateTime $start)
    {
        $this->title = $title;
        $this->startDate = $start;
    }
```

**Comment by ibrasdev** [comment]
This is the same code that i have in Event; nothing changes still got the error on doctrine:fixtures:load and on the calendar page Error: Call to a member function format() on null

If the db is empty i got : [] on a blank page
but if i add something in the db i got : {"error":"Could not convert database value \"\" to Doctrine Type array"}

**Comment by PATATESUPREME** [comment]
The construct needs additionnal parameters, so change your fixture :
```php
$schedule = new Schedule();
$schedule->setTitle('Yoga class');
$today = new \DateTime();
$schedule->setStartDate($today);
```
to
```php
$today = new \DateTime();
$schedule = new Schedule('Yoga class', $today);
```

**Comment by ibrasdev** [comment]
Merci patate.

I dont have more errors on the page but when i acces "full-calendar/load" i have an array with the correct informations in the DB ! Yeah :) But when i show the calendar there is no events !

**Comment by PATATESUPREME** [comment]
You're Welcome !

At least you made some progress.

**Comment by ibrasdev** [comment]
Yes Grace à toi :)

But why i dont get events on the calendar layout ?

**Comment by PATATESUPREME** [comment]
When you're on the calendar layout. What does the profiler says about your ajax requests ?

**Comment by ibrasdev** [comment]
The profiler shows : 

POST | xhr | 404 | /full-calendar/load | 26ms | n/a

**Comment by PATATESUPREME** [comment]
Did you add the code below in your routing.yml ?
```yml
ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"
```

**Comment by ibrasdev** [comment]
Yes of course when i access app_dev.php/full-calendar/load i got the events from the table on an array,
But in the layout cant get events and my ajax request still 404

**Comment by PATATESUPREME** [comment]
Try to clear the cache of the prod environnement.

**Comment by ibrasdev** [comment]
Ive clear the DEV&PROD cache but nothing changes, i got the same error and my ajax request still 404 :-(
![1](https://user-images.githubusercontent.com/35338949/34954523-9c8efe48-fa18-11e7-8746-934a526c12c7.png)
![2](https://user-images.githubusercontent.com/35338949/34954604-f26bd692-fa18-11e7-9264-62448405d0f0.png)

![2](https://user-images.githubusercontent.com/35338949/34954584-dc8b9808-fa18-11e7-8b1a-6927553c35c7.png)

**Comment by PATATESUPREME** [comment]
Is FOSJsRouting config properly ?

**Comment by ibrasdev** [comment]
Yeah ive already config it jsrouting-bundle version 1.6.1.

**Comment by ibrasdev** [comment]
There is a way to know that ive config well the jsrouting ?

**Comment by PATATESUPREME** [comment]
Sorry @ibrasdev,
I'm out of time for today. I'll be back tomorrow.

**Comment by ancarebeca** [comment]
Thank you very much @PATATESUPREME 👍  for your collaboration on this issue. Looks like the original issue was solved, I am going to close this.
